/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "jing-blog",
  "description": "this is a blog",
  "base": "/jing-byte.github.io/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/jing-byte.github.io/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "first page in category2",
      "frontmatter": {
        "title": "first page in category2",
        "date": "2016-12-15T00:00:00.000Z",
        "tags": [
          "tag3"
        ],
        "categories": [
          "category2"
        ]
      },
      "regularPath": "/blogs/category2/2016/121501.html",
      "relativePath": "blogs/category2/2016/121501.md",
      "key": "v-498f1437",
      "path": "/blogs/category2/2016/121501.html",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Keep Learning，持续精进",
        "tagline": "this is jing blog",
        "bgImageStyle": {
          "height": "450px"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-239bb512",
      "path": "/",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "first page in category1",
      "frontmatter": {
        "title": "first page in category1",
        "date": "2018-12-15T00:00:00.000Z",
        "tags": [
          "tag1"
        ],
        "categories": [
          "category1"
        ]
      },
      "regularPath": "/blogs/category1/2018/121501.html",
      "relativePath": "blogs/category1/2018/121501.md",
      "key": "v-2f5b1052",
      "path": "/blogs/category1/2018/121501.html",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "vuepress-theme-reco",
      "frontmatter": {
        "title": "vuepress-theme-reco",
        "date": "2019-04-09T00:00:00.000Z"
      },
      "regularPath": "/blogs/other/guide.html",
      "relativePath": "blogs/other/guide.md",
      "key": "v-462cb04a",
      "path": "/blogs/other/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Use",
          "slug": "use"
        },
        {
          "level": 2,
          "title": "Play Together",
          "slug": "play-together"
        },
        {
          "level": 3,
          "title": "0.x",
          "slug": "_0-x"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 3,
          "title": "CLI",
          "slug": "cli"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ],
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "second page in category2",
      "frontmatter": {
        "title": "second page in category2",
        "date": "2017-09-21T00:00:00.000Z",
        "tags": [
          "tag4"
        ],
        "categories": [
          "category2"
        ]
      },
      "regularPath": "/blogs/category2/2017/092101.html",
      "relativePath": "blogs/category2/2017/092101.md",
      "key": "v-0cf1b077",
      "path": "/blogs/category2/2017/092101.html",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "second page in category1",
      "frontmatter": {
        "title": "second page in category1",
        "date": "2019-09-21T00:00:00.000Z",
        "tags": [
          "tag2"
        ],
        "categories": [
          "category1"
        ]
      },
      "regularPath": "/blogs/category1/2019/092101.html",
      "relativePath": "blogs/category1/2019/092101.md",
      "key": "v-a895d7d2",
      "path": "/blogs/category1/2019/092101.html",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "theme-reco",
      "frontmatter": {
        "title": "theme-reco",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/",
      "relativePath": "docs/theme-reco/README.md",
      "key": "v-312ed407",
      "path": "/docs/theme-reco/",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "api",
      "frontmatter": {
        "title": "api",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/api.html",
      "relativePath": "docs/theme-reco/api.md",
      "key": "v-0ed11e38",
      "path": "/docs/theme-reco/api.html",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "plugin",
      "frontmatter": {
        "title": "plugin",
        "date": "2020-05-28T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/plugin.html",
      "relativePath": "docs/theme-reco/plugin.md",
      "key": "v-41a478fa",
      "path": "/docs/theme-reco/plugin.html",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "theme",
      "frontmatter": {
        "title": "theme",
        "date": "2020-05-27T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/theme.html",
      "relativePath": "docs/theme-reco/theme.md",
      "key": "v-4336c2f8",
      "path": "/docs/theme-reco/theme.html",
      "lastUpdated": "2022/7/25 10:33:51"
    },
    {
      "title": "JS基础",
      "frontmatter": {
        "title": "JS基础",
        "categories": "教程",
        "tags": [
          "js"
        ]
      },
      "regularPath": "/src/js/js.html",
      "relativePath": "src/js/js.md",
      "key": "v-32734de4",
      "path": "/src/js/js.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是跨域",
          "slug": "什么是跨域"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag3 Tags"
      },
      "regularPath": "/tag/tag3/",
      "key": "v-1368f1e8",
      "path": "/tag/tag3/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag1 Tags"
      },
      "regularPath": "/tag/tag1/",
      "key": "v-1368f264",
      "path": "/tag/tag1/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag4 Tags"
      },
      "regularPath": "/tag/tag4/",
      "key": "v-1368f1aa",
      "path": "/tag/tag4/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag2 Tags"
      },
      "regularPath": "/tag/tag2/",
      "key": "v-1368f226",
      "path": "/tag/tag2/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js Tags"
      },
      "regularPath": "/tag/js/",
      "key": "v-e8d86dc8",
      "path": "/tag/js/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "category2 Categories"
      },
      "regularPath": "/categories/category2/",
      "key": "v-5ce69b59",
      "path": "/categories/category2/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "category1 Categories"
      },
      "regularPath": "/categories/category1/",
      "key": "v-5ce69b3a",
      "path": "/categories/category1/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "教程 Categories"
      },
      "regularPath": "/categories/%E6%95%99%E7%A8%8B/",
      "key": "v-4dca6a7e",
      "path": "/categories/教程/"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 3,
    "navBar": true,
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "js",
        "items": [
          {
            "text": "js杂记",
            "link": "/src/js/js"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/theme-reco/": [
        {
          "title": "js杂记",
          "children": [
            "js"
          ]
        }
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "Category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "friendLink": [
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "logo": "/logo.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "author": "air",
    "authorAvatar": "/avatar.png",
    "record": "xxxx",
    "startYear": "2017"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}