/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "jing-blog",
  "description": "this is a blog",
  "base": "/jing-byte.github.io/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/jing-byte.github.io/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "JS",
      "frontmatter": {
        "title": "JS",
        "sidebar": "auto",
        "collapsable": true,
        "tags": [
          "js基础"
        ]
      },
      "regularPath": "/src/js/js.html",
      "relativePath": "src/js/js.md",
      "key": "v-32734de4",
      "path": "/src/js/js.html",
      "lastUpdated": "2022/7/25 15:10:26"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Keep Learning，持续精进",
        "tagline": "this is jing blog"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-239bb512",
      "path": "/",
      "lastUpdated": "2022/7/25 15:10:26"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js基础 Tags"
      },
      "regularPath": "/tag/js%E5%9F%BA%E7%A1%80/",
      "key": "v-26d3c584",
      "path": "/tag/js基础/"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 3,
    "navBar": true,
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "js",
        "items": [
          {
            "text": "js杂记",
            "link": "/src/js/js"
          }
        ]
      }
    ],
    "sidebar": {
      "/src/js/": [
        {
          "title": "js杂记",
          "children": [
            "js"
          ]
        }
      ]
    },
    "logo": "/logo.png",
    "search": true
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}