/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "js基础": {
      "key": "js基础",
      "scope": "tags",
      "path": "/tag/js基础/",
      "pageKeys": [
        "v-32734de4"
      ]
    }
  },
  "categories": {},
  "timeline": {}
}