/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "tag3": {
      "key": "tag3",
      "scope": "tags",
      "path": "/tag/tag3/",
      "pageKeys": [
        "v-498f1437"
      ]
    },
    "tag1": {
      "key": "tag1",
      "scope": "tags",
      "path": "/tag/tag1/",
      "pageKeys": [
        "v-2f5b1052"
      ]
    },
    "tag4": {
      "key": "tag4",
      "scope": "tags",
      "path": "/tag/tag4/",
      "pageKeys": [
        "v-0cf1b077"
      ]
    },
    "tag2": {
      "key": "tag2",
      "scope": "tags",
      "path": "/tag/tag2/",
      "pageKeys": [
        "v-a895d7d2"
      ]
    },
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tag/js/",
      "pageKeys": [
        "v-32734de4"
      ]
    }
  },
  "categories": {
    "category2": {
      "key": "category2",
      "scope": "categories",
      "path": "/categories/category2/",
      "pageKeys": [
        "v-498f1437",
        "v-0cf1b077"
      ]
    },
    "category1": {
      "key": "category1",
      "scope": "categories",
      "path": "/categories/category1/",
      "pageKeys": [
        "v-2f5b1052",
        "v-a895d7d2"
      ]
    },
    "教程": {
      "key": "教程",
      "scope": "categories",
      "path": "/categories/教程/",
      "pageKeys": [
        "v-32734de4"
      ]
    }
  },
  "timeline": {}
}