/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "js基础",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/js基础/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]